# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dotnet-simple-booking-system

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_953423833b8f4162904eb98a8b765ac4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_497f2a73953e42b68c1afbd91521de72 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_953423833b8f4162904eb98a8b765ac4 }}/dotnet-simple-booking-system:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dotnet-simple-booking-system'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3459d1937336459e987583acc42a43eb }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_953423833b8f4162904eb98a8b765ac4 }}/dotnet-simple-booking-system:${{ github.sha }}'